AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'

# The "offical" rubocop style guide is indeed quite strict. So intead, we use
# the Relaxed Ruby Style guide. https://relaxed.ruby.style/

inherit_gem:
  relaxed-rubocop: .rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

Style/RedundantSelf:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Lint/UselessAssignment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: ending_only

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/RedundantReturn:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/NumericLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2, 3, 4, 5]

Style/CommentedKeyword:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Style/RescueModifier:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Layout/DotPosition:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/**/*.rb'
    - 'app/models/ahoy/{event,visit}.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Rails/RequestReferer:
  EnforcedStyle: referrer

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Validation:
  Enabled: false

# Custom finder methods that are NOT Rails dynamic finders
Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email      # User.find_by_email - custom method
    - find_by_date       # Term.find_by_date - custom method
    - find_by_public_id  # PublicIdentifiable concern method

Rails/UniqueValidationWithoutIndex:
  Enabled: false

# RSpec configuration
RSpec/DescribeClass:
  Exclude:
    - 'spec/config/**/*'
    - 'spec/requests/**/*'

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

# Rails cops for specs
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
    - 'tmp/migrated/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

# Allow empty factory blocks
Lint/EmptyBlock:
  Exclude:
    - 'spec/factories/**/*'

# Naming cops
# PredicateMethod: Methods like sync_course_data are not predicates despite what the cop thinks
Naming/PredicateMethod:
  Enabled: false

# VariableNumber: Allow symbols with numbers like :fall_2025 for term naming
Naming/VariableNumber:
  Exclude:
    - 'app/services/finals_schedule_parser_service.rb'
    - 'spec/**/*'

# Style cops
# SafeNavigationChainLength: Allow longer chains for concise nil-safe operations
Style/SafeNavigationChainLength:
  Enabled: false

# Additional RSpec configurations for spec maintainability
# Complex test suites often need more helpers and expectations

RSpec/MultipleMemoizedHelpers:
  Max: 20

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Max: 30

RSpec/NestedGroups:
  Max: 5

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/factories/**/*'

RSpec/EmptyLineAfterExampleGroup:
  Exclude:
    - 'spec/factories/**/*'

RSpec/RepeatedDescription:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false