# frozen_string_literal: true

module TwentyFiveLive
  class SpaceFeature
    SPACE_FEATURES = [
      { feature_id: 2,  feature_name: "Access - Card",                              defn_state: 1, tag: "LeopardSpot" },
      { feature_id: 3,  feature_name: "Access - Key",                               defn_state: 1, tag: nil },
      { feature_id: 4,  feature_name: "ADA - Assisted Listening System (ALS)",      defn_state: 1, tag: nil },
      { feature_id: 5,  feature_name: "ADA - Wheelchair Accessible",                defn_state: 1, tag: nil },
      { feature_id: 6,  feature_name: "Air Conditioning",                           defn_state: 1, tag: nil },
      { feature_id: 7,  feature_name: "AV - Blu-ray",                               defn_state: 1, tag: nil },
      { feature_id: 8,  feature_name: "AV - Conference Phone",                      defn_state: 1, tag: nil },
      { feature_id: 9,  feature_name: "AV - Document Camera",                       defn_state: 1, tag: nil },
      { feature_id: 10, feature_name: "AV - In Room PC",                            defn_state: 1, tag: nil },
      { feature_id: 11, feature_name: "AV - Instructor Desk",                       defn_state: 1, tag: nil },
      { feature_id: 12, feature_name: "Internet - Wired",                           defn_state: 1, tag: nil },
      { feature_id: 13, feature_name: "Internet - Wireless",                        defn_state: 1, tag: nil },
      { feature_id: 14, feature_name: "AV - Laptop Connection - HDMI",              defn_state: 1, tag: nil },
      { feature_id: 15, feature_name: "AV - Laptop Connection - Wireless (Air Media)", defn_state: 1, tag: nil },
      { feature_id: 16, feature_name: "AV - Lecture Capture",                       defn_state: 1, tag: nil },
      { feature_id: 17, feature_name: "AV - Microphone - Podium",                   defn_state: 1, tag: nil },
      { feature_id: 18, feature_name: "AV - Microphone - Wireless Handheld",        defn_state: 1, tag: nil },
      { feature_id: 19, feature_name: "AV - Microphone - Wireless Lavalier",        defn_state: 1, tag: nil },
      { feature_id: 20, feature_name: "AV - None",                                  defn_state: 1, tag: nil },
      { feature_id: 21, feature_name: "AV - Projector",                             defn_state: 1, tag: nil },
      { feature_id: 22, feature_name: "AV - Screen Type - Projector Screen",        defn_state: 1, tag: nil },
      { feature_id: 23, feature_name: "AV - Screen Type - TV",                      defn_state: 1, tag: nil },
      { feature_id: 24, feature_name: "AV - Screen Type - Whiteboard",              defn_state: 1, tag: nil },
      { feature_id: 25, feature_name: "AV - Sound System",                          defn_state: 1, tag: nil },
      { feature_id: 26, feature_name: "AV - Video Conferencing Capable",            defn_state: 1, tag: nil },
      { feature_id: 27, feature_name: "AV - Zoom Cart",                             defn_state: 1, tag: nil },
      { feature_id: 28, feature_name: "Board - Whiteboard",                         defn_state: 1, tag: nil },
      { feature_id: 29, feature_name: "Floor - Carpet",                             defn_state: 1, tag: nil },
      { feature_id: 30, feature_name: "Floor - Concrete",                           defn_state: 1, tag: nil },
      { feature_id: 31, feature_name: "Floor - Hardwood",                           defn_state: 1, tag: nil },
      { feature_id: 32, feature_name: "Floor - Tile",                               defn_state: 1, tag: nil },
      { feature_id: 33, feature_name: "Lighting - Dimmable",                        defn_state: 1, tag: nil },
      { feature_id: 34, feature_name: "Piano",                                       defn_state: 1, tag: nil },
      { feature_id: 35, feature_name: "Podium - Fixed",                             defn_state: 1, tag: nil },
      { feature_id: 36, feature_name: "Podium - Portable",                          defn_state: 1, tag: nil },
      { feature_id: 37, feature_name: "Seating - Drafting Tables & Stools (DRF)",   defn_state: 1, tag: nil },
      { feature_id: 38, feature_name: "Seating - Fixed",                            defn_state: 1, tag: nil },
      { feature_id: 39, feature_name: "Seating - Moveable Desk",                    defn_state: 1, tag: nil },
      { feature_id: 40, feature_name: "Seating - None",                             defn_state: 1, tag: nil },
      { feature_id: 41, feature_name: "Seating - Powered Desk",                     defn_state: 1, tag: nil },
      { feature_id: 42, feature_name: "Seating - Soft Seating",                     defn_state: 1, tag: nil },
      { feature_id: 43, feature_name: "Seating - Tables & Chairs (TAC)",            defn_state: 1, tag: nil },
      { feature_id: 44, feature_name: "Seating - Tablet Arm Chair (TAB)",           defn_state: 1, tag: nil },
      { feature_id: 45, feature_name: "Seating - Writable Surface Desk",            defn_state: 1, tag: nil },
      { feature_id: 46, feature_name: "Stage",                                       defn_state: 1, tag: nil },
      { feature_id: 47, feature_name: "Windows - External",                         defn_state: 1, tag: nil },
      { feature_id: 48, feature_name: "Windows - Internal",                         defn_state: 1, tag: nil },
      { feature_id: 50, feature_name: "Sodexo - No Catering Available",             defn_state: 1, tag: nil }
    ].freeze
  end
end
