# frozen_string_literal: true

module TwentyFiveLive
  class SpaceFeature
    SPACE_FEATURES = [
      { feature_id: 2,  feature_name: "Access-Card",                      defn_state: 1, tag: "LeopardSpot" },
      { feature_id: 3,  feature_name: "Access-Key",                       defn_state: 1, tag: nil },
      { feature_id: 4,  feature_name: "ADA - Accessible Entrance",        defn_state: 1, tag: nil },
      { feature_id: 5,  feature_name: "ADA - Accessible Path of Travel",  defn_state: 1, tag: nil },
      { feature_id: 6,  feature_name: "ADA - Accessible Restroom Nearby", defn_state: 1, tag: nil },
      { feature_id: 7,  feature_name: "ADA - Assistive Listening Device", defn_state: 1, tag: nil },
      { feature_id: 8,  feature_name: "ADA - Elevator Access",            defn_state: 1, tag: nil },
      { feature_id: 9,  feature_name: "ADA - Wheelchair Accessible",      defn_state: 1, tag: nil },
      { feature_id: 10, feature_name: "AV - Blu-ray Player",              defn_state: 1, tag: nil },
      { feature_id: 11, feature_name: "AV - Cable TV",                    defn_state: 1, tag: nil },
      { feature_id: 12, feature_name: "AV - Document Camera",             defn_state: 1, tag: nil },
      { feature_id: 13, feature_name: "AV - DVD Player",                  defn_state: 1, tag: nil },
      { feature_id: 14, feature_name: "AV - LCD Projector",               defn_state: 1, tag: nil },
      { feature_id: 15, feature_name: "AV - Microphone",                  defn_state: 1, tag: nil },
      { feature_id: 16, feature_name: "AV - Presentation Screen",         defn_state: 1, tag: nil },
      { feature_id: 17, feature_name: "AV - Sound System",                defn_state: 1, tag: nil },
      { feature_id: 18, feature_name: "AV - TV Monitor",                  defn_state: 1, tag: nil },
      { feature_id: 19, feature_name: "AV - Video Conferencing",          defn_state: 1, tag: nil },
      { feature_id: 20, feature_name: "AV - Whiteboard",                  defn_state: 1, tag: nil },
      { feature_id: 21, feature_name: "Floor - Carpet",                   defn_state: 1, tag: nil },
      { feature_id: 22, feature_name: "Floor - Hardwood",                 defn_state: 1, tag: nil },
      { feature_id: 23, feature_name: "Floor - Tile",                     defn_state: 1, tag: nil },
      { feature_id: 24, feature_name: "Seating - Auditorium",             defn_state: 1, tag: nil },
      { feature_id: 25, feature_name: "Seating - Movable",                defn_state: 1, tag: nil },
      { feature_id: 26, feature_name: "Seating - Theater Style",          defn_state: 1, tag: nil },
      { feature_id: 27, feature_name: "Seating - Tiered",                 defn_state: 1, tag: nil },
      { feature_id: 28, feature_name: "Window - Blackout Shades",         defn_state: 1, tag: nil },
      { feature_id: 29, feature_name: "Window - Natural Light",           defn_state: 1, tag: nil },
      { feature_id: 30, feature_name: "AV - HDMI",                        defn_state: 1, tag: nil },
      { feature_id: 31, feature_name: "AV - Laser Projector",             defn_state: 1, tag: nil },
      { feature_id: 32, feature_name: "AV - Wireless Presentation",       defn_state: 1, tag: nil },
      { feature_id: 33, feature_name: "Seating - Fixed",                  defn_state: 1, tag: nil },
      { feature_id: 34, feature_name: "AV - Computer",                    defn_state: 1, tag: nil },
      { feature_id: 35, feature_name: "ADA - Accessible Seating",        defn_state: 1, tag: nil },
      { feature_id: 36, feature_name: "AV - Smart Board",                 defn_state: 1, tag: nil },
      { feature_id: 37, feature_name: "Seating - Booth",                  defn_state: 1, tag: nil },
      { feature_id: 38, feature_name: "Seating - Stool",                  defn_state: 1, tag: nil },
      { feature_id: 39, feature_name: "AV - Apple TV",                    defn_state: 1, tag: nil },
      { feature_id: 40, feature_name: "AV - Classroom Capture",           defn_state: 1, tag: nil },
      { feature_id: 41, feature_name: "AV - Dual Screen",                 defn_state: 1, tag: nil },
      { feature_id: 42, feature_name: "AV - Polycom",                     defn_state: 1, tag: nil },
      { feature_id: 43, feature_name: "AV - Zoom Room",                   defn_state: 1, tag: nil },
      { feature_id: 44, feature_name: "Floor - Vinyl",                    defn_state: 1, tag: nil },
      { feature_id: 45, feature_name: "Seating - Lounge",                 defn_state: 1, tag: nil },
      { feature_id: 46, feature_name: "Seating - Standing",               defn_state: 1, tag: nil },
      { feature_id: 47, feature_name: "Window - None",                    defn_state: 1, tag: nil },
      { feature_id: 48, feature_name: "AV - Annotation Display",          defn_state: 1, tag: nil },
      { feature_id: 49, feature_name: "AV - Microsoft Teams Room",        defn_state: 1, tag: nil },
      { feature_id: 50, feature_name: "Sodexo No Catering",               defn_state: 1, tag: nil }
    ].freeze
  end
end
